name: Tests

on:
    push:
        branches: [ master ]
    pull_request:

jobs:

    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.1', '7.2', '7.3', '7.4']
        steps:

        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ matrix.php-versions }}
              tools: pecl
              extensions: uopz
          env:
              update: true

        - name: Get dependencies
          run: composer install
          env:
              COMPOSER_MEMORY_LIMIT: -1
              COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Get tools
          run: |
              cd dev-tools
              composer install

        - name: Check coding standards
          run: |
              ./dev-tools/vendor/bin/php-cs-fixer --diff --dry-run -v --allow-risky=yes fix
              ./dev-tools/vendor/bin/php-cs-fixer --diff --dry-run -v --allow-risky=yes fix .php_cs.dist

        - name: Test
          run: vendor/bin/phpunit
